### ISSUE TITLE
Struggling in species-specific intercept

### ISSUE THREAD

**Issue by bserranito** [skiptoniam/ecomix#35]
Hi,
Following recommendations of Dunstan et al., (2013), i want to include a species-specific interpt in my SAM model using the "species formula" argument of species.mix function. However, in struggling to find relevant information or explicit example on how to properly  manage it.

I currently my attempt to specify it follow the formulation of the "archetype formula" argument  :
 "cbind(spp1,spp2,spp3...) ~ c(intercept1, intercept2, intercept3...).

However, this way was unsuccessful...

Could you please provide me with an example or offer some advice on how to proceed with this issue?

Thank you.

**Comment by skiptoniam** [comment]
Hi @bserranito,

The species specific intercept is fitted by default. Via the `species_formula = ~ 1`, we don't actually support the archetype intercept anymore (but in theory we could implement it if really need). At some point I intend to extend the species formula to allow for covariates on the species at well as the archetypes, this would look something like the model in Foster et al., 2015: https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/1365-2664.12353.

So for the archetype formula it'd be something like:
`cbind(spp1,...,sppN) ~ covar1 + covar2`

Even if you include an intercept in the archetype formula it get's dropped internally.
 
And the species formula would be:
`~1` (default setting)

Yell out if this doesn't make sense.

Cheers,

Skip.

**Comment by skiptoniam** [comment]
@bserranito I'm going to close this issue. Feel free to open it up again if you're still having problems
