### ISSUE TITLE
Species-level predictions species_mix

### ISSUE THREAD

**Issue by fhui28** [skiptoniam/ecomix#36]
More a conceptual question than anything (since I am starting to work on the approximate SAMs idea!): I noticed when performing uncertainty quantification (using the bootstrap) for species-level predictions in `species_mix`, the posterior probabilities are conditioned on i.e., the `tau` does not change with bootstrapped datasets e.g., tau is a supplied argument in the internal function `sam_internal_pred_species`. 

Should we condition on them, or should we (also) recompute tau for each new bootstrapped dataset since they are, after all, also functions of the parameters. I do not know, but would be curious to hear from you and potentially @Scott-Foster and @pdog-extreme as well...although perhaps you answered this already in another paper? 

Cheers.

**Comment by skiptoniam** [comment]
I think that was on my to do list. I think I originally left tau as the taus from the initial fit because they don't change that much. But I think it's a good idea and we I can look to implementing that.

**Comment by fhui28** [comment]
Fair enough...yeah it does not surprise me that it does not change much give that SAMs tend to classify pretty "hard", but sounds like a plan!
